CC=g++
CFLAGS=-Wall

caesar:
	$(CC) $(CFLAGS) caesar.cc -o caesar

atoi:
	$(CC) $(CFLAGS) atoi.cc -o atoi

palindrome:
	$(CC) $(CFLAGS) palindrome.cc -o pal

rpmb:
	$(CC) $(CFLAGS) rpmb.cc -o rpmb

clean:
	rm -f caesar atoi pal
