CC=g++
CFLAGS=-Wall -std=c++0x

rob: robber.cc
	$(CC) $(CFLAGS) robber.cc -o rob

wb: wordbreak.cc
	$(CC) $(CFLAGS) wordbreak.cc -o wb

ps: parentheses.cc
	$(CC) $(CFLAGS) parentheses.cc -o ps

box: boxes.cc
	$(CC) $(CFLAGS) boxes.cc -o box

clean:
	rm -rf rob wb ps box
